### ISSUE TITLE
bị lỗi không thể chạy được

### ISSUE THREAD

**Issue by hoangquangtuongxDevelopers** [XaviaTeam/facebook-bot-chatgpt#1]
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:393:5)
    at Function.from (node:buffer:328:9)
    at base64Decode (file:///home/runner/facebook-bot-chatgpt/node_modules/fca-utils/lib/utils.js:8:19)
    at getAppstate (file:///home/runner/facebook-bot-chatgpt/node_modules/fca-utils/lib/utils.js:11:23)
    at Client.loginWithAppState (file:///home/runner/facebook-bot-chatgpt/node_modules/fca-utils/lib/index.js:77:26)
    at file:///home/runner/facebook-bot-chatgpt/index.js:17:8
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by RFS-ADRENO** [comment]
gắn appstate (base64) vào biến môi trường như hướng dẫn trong readme nhé
